model_params:
  model: SimpleNet

args:
  expdir: "expdir"
  logdir: "./logs/cifar"

stages:
  data_params:
    batch_size: 64
    num_workers: 1
    my_seed: 4

  state_params:
    num_epochs: 2
    main_metric: &reduce_metric accuracy01
    minimize_metric: False
    num_classes: &num_classes 10
    class_names: &class_names [
      'plane', 'car', 'bird', 'cat',
      'deer', 'dog', 'frog', 'horse', 'ship', 'truck'
    ]

  criterion_params:
    criterion: CrossEntropyLoss

  scheduler_params:
    scheduler: MultiStepLR
    milestones: [10]
    gamma: 0.3

  callbacks_params:
    loss:
      callback: CriterionCallback
    optimizer:
      callback: OptimizerCallback
    accuracy:
      callback: AccuracyCallback
      accuracy_args: [1, 3, 5]
    scheduler:
      callback: SchedulerCallback
      reduce_metric: *reduce_metric
    saver:
      callback: CheckpointCallback
    cm:
      callback: ConfusionMatrixCallback
      num_classes: *num_classes
      class_names: *class_names

  stage1:
    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

  # tune
  stage2:
    state_params:
      num_epochs: 3

    optimizer_params:
      optimizer: Adam
      lr: 0.0001
      weight_decay: 0.0001
